name = "fantasy"
main = "worker/index.js"
compatibility_date = "2026-04-06"

[build]
command = "npm run build"

[assets]
directory = "./client/dist"
binding = "ASSETS"
not_found_handling = "single-page-application"

[[d1_databases]]
binding = "DB"
database_name = "fantasyhockey"
database_id = "947587fd-a195-4f3a-adcc-874a9f35e906"
migrations_dir = "migrations"

[vars]
NODE_ENV = "production"

[triggers]
crons = ["0 * * * *"]
